"""
PDF Generation Service for Innovation Results
"""

import io
from datetime import datetime
from typing import Dict, Any, List
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.colors import Color, HexColor
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
import logging

logger = logging.getLogger(__name__)


class PDFService:
    """Service for generating PDF reports of innovation results"""
    
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
    
    def _setup_custom_styles(self):
        """Setup custom paragraph styles for the PDF"""
        # Title style
        self.styles.add(ParagraphStyle(
            name='InnovationTitle',
            parent=self.styles['Title'],
            fontSize=24,
            spaceAfter=30,
            alignment=TA_CENTER,
            textColor=HexColor('#1976d2'),
            fontName='Helvetica-Bold'
        ))
        
        # Subtitle style
        self.styles.add(ParagraphStyle(
            name='InnovationSubtitle',
            parent=self.styles['Heading1'],
            fontSize=16,
            spaceAfter=20,
            textColor=HexColor('#333333'),
            fontName='Helvetica-Bold'
        ))
        
        # Content style
        self.styles.add(ParagraphStyle(
            name='InnovationContent',
            parent=self.styles['Normal'],
            fontSize=12,
            spaceAfter=12,
            alignment=TA_JUSTIFY,
            fontName='Helvetica'
        ))
        
        # Meta info style
        self.styles.add(ParagraphStyle(
            name='InnovationMeta',
            parent=self.styles['Normal'],
            fontSize=10,
            spaceAfter=6,
            textColor=HexColor('#666666'),
            fontName='Helvetica-Oblique'
        ))

    def generate_combination_pdf(self, result: Dict[str, Any], user_info: Dict[str, Any] = None) -> bytes:
        """Generate PDF for innovation combination result"""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=1*inch)
        
        story = []
        
        # Header
        story.append(Paragraph("Innovation Hub", self.styles['InnovationTitle']))
        story.append(Paragraph("Idea Combination Report", self.styles['InnovationSubtitle']))
        story.append(Spacer(1, 20))
        
        # Metadata
        meta_info = [
            f"<b>Generated:</b> {datetime.now().strftime('%B %d, %Y at %I:%M %p')}",
            f"<b>Type:</b> {result.get('type', 'combination').title()}",
            f"<b>Novelty Score:</b> {(result.get('novelty_score', 0) * 100):.0f}%"
        ]
        
        if result.get('combination_type'):
            meta_info.append(f"<b>Combination Type:</b> {result['combination_type'].title()}")
        
        if user_info:
            meta_info.append(f"<b>Generated by:</b> {user_info.get('full_name', user_info.get('username', 'User'))}")
        
        for meta in meta_info:
            story.append(Paragraph(meta, self.styles['InnovationMeta']))
        
        story.append(Spacer(1, 20))
        
        # Title
        story.append(Paragraph("Innovation Result", self.styles['InnovationSubtitle']))
        story.append(Spacer(1, 10))
        
        # Content
        content = result.get('content', 'No content available')
        # Convert line breaks to HTML breaks for proper formatting
        content_html = content.replace('\n', '<br/>')
        story.append(Paragraph(content_html, self.styles['InnovationContent']))
        
        # Expansion suggestions
        if result.get('expansion_suggestions') and len(result['expansion_suggestions']) > 0:
            story.append(Spacer(1, 20))
            story.append(Paragraph("Expansion Suggestions", self.styles['InnovationSubtitle']))
            story.append(Spacer(1, 10))
            
            suggestions_data = []
            for i, suggestion in enumerate(result['expansion_suggestions'], 1):
                suggestion_text = suggestion if isinstance(suggestion, str) else suggestion.get('suggestion', str(suggestion))
                suggestions_data.append([f"{i}.", suggestion_text])
            
            if suggestions_data:
                suggestions_table = Table(suggestions_data, colWidths=[0.5*inch, 6*inch])
                suggestions_table.setStyle(TableStyle([
                    ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                    ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                    ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
                    ('FONTSIZE', (0, 0), (-1, -1), 10),
                    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                ]))
                story.append(suggestions_table)
        
        # Footer
        story.append(Spacer(1, 40))
        story.append(Paragraph(
            f"Generated by Idea Innovation Hub - {datetime.now().strftime('%Y')}",
            self.styles['InnovationMeta']
        ))
        
        doc.build(story)
        buffer.seek(0)
        return buffer.getvalue()

    def generate_expansion_pdf(self, result: Dict[str, Any], user_info: Dict[str, Any] = None) -> bytes:
        """Generate PDF for innovation expansion result"""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=1*inch)
        
        story = []
        
        # Header
        story.append(Paragraph("Innovation Hub", self.styles['InnovationTitle']))
        story.append(Paragraph("Idea Expansion Report", self.styles['InnovationSubtitle']))
        story.append(Spacer(1, 20))
        
        # Metadata
        meta_info = [
            f"<b>Generated:</b> {datetime.now().strftime('%B %d, %Y at %I:%M %p')}",
            f"<b>Type:</b> {result.get('type', 'expansion').title()}",
            f"<b>Feasibility Score:</b> {(result.get('feasibility_score', 0) * 100):.0f}%"
        ]
        
        if result.get('expansion_type'):
            meta_info.append(f"<b>Expansion Type:</b> {result['expansion_type'].title()}")
        
        if user_info:
            meta_info.append(f"<b>Generated by:</b> {user_info.get('full_name', user_info.get('username', 'User'))}")
        
        for meta in meta_info:
            story.append(Paragraph(meta, self.styles['InnovationMeta']))
        
        story.append(Spacer(1, 20))
        
        # Title
        story.append(Paragraph("Expanded Innovation", self.styles['InnovationSubtitle']))
        story.append(Spacer(1, 10))
        
        # Content
        content = result.get('content', 'No content available')
        content_html = content.replace('\n', '<br/>')
        story.append(Paragraph(content_html, self.styles['InnovationContent']))
        
        # Footer
        story.append(Spacer(1, 40))
        story.append(Paragraph(
            f"Generated by Idea Innovation Hub - {datetime.now().strftime('%Y')}",
            self.styles['InnovationMeta']
        ))
        
        doc.build(story)
        buffer.seek(0)
        return buffer.getvalue()

    def generate_suggestions_pdf(self, result: Dict[str, Any], user_info: Dict[str, Any] = None) -> bytes:
        """Generate PDF for innovation suggestions result"""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=1*inch)
        
        story = []
        
        # Header
        story.append(Paragraph("Innovation Hub", self.styles['InnovationTitle']))
        story.append(Paragraph("AI Suggestions Report", self.styles['InnovationSubtitle']))
        story.append(Spacer(1, 20))
        
        # Metadata
        meta_info = [
            f"<b>Generated:</b> {datetime.now().strftime('%B %d, %Y at %I:%M %p')}",
            f"<b>Type:</b> {result.get('type', 'suggestions').title()}"
        ]
        
        if user_info:
            meta_info.append(f"<b>Generated by:</b> {user_info.get('full_name', user_info.get('username', 'User'))}")
        
        for meta in meta_info:
            story.append(Paragraph(meta, self.styles['InnovationMeta']))
        
        story.append(Spacer(1, 20))
        
        # Title
        story.append(Paragraph("AI-Powered Suggestions", self.styles['InnovationSubtitle']))
        story.append(Spacer(1, 10))
        
        # Content
        content = result.get('content', 'No content available')
        content_html = content.replace('\n', '<br/>')
        story.append(Paragraph(content_html, self.styles['InnovationContent']))
        
        # Detailed suggestions
        if result.get('suggestions') and len(result['suggestions']) > 0:
            story.append(Spacer(1, 20))
            story.append(Paragraph("Detailed Suggestions", self.styles['InnovationSubtitle']))
            story.append(Spacer(1, 10))
            
            for i, suggestion in enumerate(result['suggestions'], 1):
                suggestion_text = suggestion.get('suggestion', str(suggestion))
                feasibility = suggestion.get('feasibility_score', 0)
                
                story.append(Paragraph(f"{i}. {suggestion_text}", self.styles['InnovationContent']))
                if feasibility > 0:
                    story.append(Paragraph(
                        f"   <i>Feasibility: {(feasibility * 100):.0f}%</i>",
                        self.styles['InnovationMeta']
                    ))
                story.append(Spacer(1, 10))
        
        # Footer
        story.append(Spacer(1, 40))
        story.append(Paragraph(
            f"Generated by Idea Innovation Hub - {datetime.now().strftime('%Y')}",
            self.styles['InnovationMeta']
        ))
        
        doc.build(story)
        buffer.seek(0)
        return buffer.getvalue()

    def generate_innovation_pdf(self, result: Dict[str, Any], user_info: Dict[str, Any] = None) -> bytes:
        """Generate PDF based on innovation type"""
        innovation_type = result.get('type', 'combination')
        
        if innovation_type == 'combination':
            return self.generate_combination_pdf(result, user_info)
        elif innovation_type == 'expansion':
            return self.generate_expansion_pdf(result, user_info)
        elif innovation_type == 'suggestions':
            return self.generate_suggestions_pdf(result, user_info)
        else:
            # Fallback to combination format
            return self.generate_combination_pdf(result, user_info)


# Create global instance
pdf_service = PDFService()
