import React, { createContext, useContext } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translation strings
const translations = {
  en: {
    // Common
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    create: 'Create',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    info: 'Info',
    
    // Navigation
    dashboard: 'Dashboard',
    ideas: 'Ideas',
    clusters: 'Clusters',
    innovation: 'Innovation',
    visualization: 'Visualization',
    settings: 'Settings',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    
    // Settings
    settings_title: 'Settings',
    profile_settings: 'Profile Settings',
    preferences: 'Preferences',
    privacy_settings: 'Privacy Settings',
    data_management: 'Data Management',
    security: 'Security',
    api_configuration: 'API Configuration',
    your_statistics: 'Your Statistics',
    total_ideas: 'Total Ideas',
    clusters_count: 'Clusters',
    innovations_count: 'Innovations',
    avg_novelty: 'Avg Novelty',
    theme: 'Theme',
    language: 'Language',
    notifications: 'Notifications',
    voice_input: 'Voice Input',
    image_upload: 'Image Upload',
    auto_clustering: 'Auto Clustering',
    allow_data_sharing: 'Allow data sharing for research',
    usage_analytics: 'Usage analytics',
    public_profile: 'Public profile',
    export_my_data: 'Export My Data',
    delete_account: 'Delete Account',
    change_password: 'Change Password',
    gemini_api_key: 'Gemini API Key',
    openai_api_key: 'OpenAI API Key',
    test_gemini_key: 'Test Gemini Key',
    test_openai_key: 'Test OpenAI Key',
    save_settings: 'Save Settings',
    saving: 'Saving...',
    
    // Help & Support
    help_support: 'Help & Support',
    frequently_asked_questions: 'Frequently Asked Questions',
    contact_us: 'Contact Us',
    getting_started_guide: 'Getting Started Guide',
    feature_overview: 'Feature Overview',
    send_message: 'Send Message',
    your_name: 'Your Name',
    email_address: 'Email Address',
    subject: 'Subject',
    message_type: 'Message Type',
    message: 'Message',
    general_question: 'General Question',
    bug_report: 'Bug Report',
    feature_request: 'Feature Request',
    technical_support: 'Technical Support',
    feedback: 'Feedback',
    sending: 'Sending...',
    thank_you_message: 'Thank you for your message! We will get back to you soon.',
    failed_to_send: 'Failed to send message. Please try again.',
    email_support: 'Email Support',
    phone_support: 'Phone Support',
    office_address: 'Office Address',
    get_help_via_email: 'Get help via email',
    call_us_immediate: 'Call us for immediate assistance',
    visit_our_office: 'Visit our office',
    send_email: 'Send Email',
    call_now: 'Call Now',
    get_directions: 'Get Directions',
    create_ideas: 'Create Ideas',
    generate_clusters: 'Generate Clusters',
    innovate: 'Innovate',
    idea_management: 'Idea Management',
    ai_clustering: 'AI Clustering',
    innovation_tools: 'Innovation Tools',
    data_export: 'Data Export',
  },
  hi: {
    // Common
    save: 'सहेजें',
    cancel: 'रद्द करें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    create: 'बनाएं',
    loading: 'लोड हो रहा है...',
    error: 'त्रुटि',
    success: 'सफलता',
    warning: 'चेतावनी',
    info: 'जानकारी',
    
    // Navigation
    dashboard: 'डैशबोर्ड',
    ideas: 'विचार',
    clusters: 'क्लस्टर',
    innovation: 'नवाचार',
    visualization: 'विज़ुअलाइज़ेशन',
    settings: 'सेटिंग्स',
    login: 'लॉगिन',
    register: 'रजिस्टर',
    logout: 'लॉगआउट',
    
    // Settings
    settings_title: 'सेटिंग्स',
    profile_settings: 'प्रोफ़ाइल सेटिंग्स',
    preferences: 'प्राथमिकताएं',
    privacy_settings: 'गोपनीयता सेटिंग्स',
    data_management: 'डेटा प्रबंधन',
    security: 'सुरक्षा',
    api_configuration: 'API कॉन्फ़िगरेशन',
    your_statistics: 'आपके आंकड़े',
    total_ideas: 'कुल विचार',
    clusters_count: 'क्लस्टर',
    innovations_count: 'नवाचार',
    avg_novelty: 'औसत नवीनता',
    theme: 'थीम',
    language: 'भाषा',
    notifications: 'सूचनाएं',
    voice_input: 'आवाज़ इनपुट',
    image_upload: 'छवि अपलोड',
    auto_clustering: 'स्वचालित क्लस्टरिंग',
    allow_data_sharing: 'अनुसंधान के लिए डेटा साझाकरण की अनुमति दें',
    usage_analytics: 'उपयोग एनालिटिक्स',
    public_profile: 'सार्वजनिक प्रोफ़ाइल',
    export_my_data: 'मेरा डेटा निर्यात करें',
    delete_account: 'खाता हटाएं',
    change_password: 'पासवर्ड बदलें',
    gemini_api_key: 'जेमिनी API कुंजी',
    openai_api_key: 'ओपनएआई API कुंजी',
    test_gemini_key: 'जेमिनी कुंजी टेस्ट करें',
    test_openai_key: 'ओपनएआई कुंजी टेस्ट करें',
    save_settings: 'सेटिंग्स सहेजें',
    saving: 'सहेजा जा रहा है...',
    
    // Help & Support
    help_support: 'सहायता और समर्थन',
    frequently_asked_questions: 'अक्सर पूछे जाने वाले प्रश्न',
    contact_us: 'हमसे संपर्क करें',
    getting_started_guide: 'शुरुआती गाइड',
    feature_overview: 'फीचर अवलोकन',
    send_message: 'संदेश भेजें',
    your_name: 'आपका नाम',
    email_address: 'ईमेल पता',
    subject: 'विषय',
    message_type: 'संदेश प्रकार',
    message: 'संदेश',
    general_question: 'सामान्य प्रश्न',
    bug_report: 'बग रिपोर्ट',
    feature_request: 'फीचर अनुरोध',
    technical_support: 'तकनीकी सहायता',
    feedback: 'प्रतिक्रिया',
    sending: 'भेजा जा रहा है...',
    thank_you_message: 'आपके संदेश के लिए धन्यवाद! हम जल्द ही आपसे संपर्क करेंगे।',
    failed_to_send: 'संदेश भेजने में विफल। कृपया पुनः प्रयास करें।',
    email_support: 'ईमेल सहायता',
    phone_support: 'फोन सहायता',
    office_address: 'कार्यालय पता',
    get_help_via_email: 'ईमेल के माध्यम से सहायता प्राप्त करें',
    call_us_immediate: 'तत्काल सहायता के लिए हमें कॉल करें',
    visit_our_office: 'हमारे कार्यालय में आएं',
    send_email: 'ईमेल भेजें',
    call_now: 'अभी कॉल करें',
    get_directions: 'दिशा-निर्देश प्राप्त करें',
    create_ideas: 'विचार बनाएं',
    generate_clusters: 'क्लस्टर जेनरेट करें',
    innovate: 'नवाचार करें',
    idea_management: 'विचार प्रबंधन',
    ai_clustering: 'AI क्लस्टरिंग',
    innovation_tools: 'नवाचार उपकरण',
    data_export: 'डेटा निर्यात',
  },
  es: {
    // Common
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    create: 'Crear',
    loading: 'Cargando...',
    error: 'Error',
    success: 'Éxito',
    warning: 'Advertencia',
    info: 'Información',
    
    // Navigation
    dashboard: 'Panel',
    ideas: 'Ideas',
    clusters: 'Clusters',
    innovation: 'Innovación',
    visualization: 'Visualización',
    settings: 'Configuración',
    login: 'Iniciar sesión',
    register: 'Registrarse',
    logout: 'Cerrar sesión',
    
    // Settings
    settings_title: 'Configuración',
    profile_settings: 'Configuración del perfil',
    preferences: 'Preferencias',
    privacy_settings: 'Configuración de privacidad',
    data_management: 'Gestión de datos',
    security: 'Seguridad',
    api_configuration: 'Configuración de API',
    your_statistics: 'Tus estadísticas',
    total_ideas: 'Ideas totales',
    clusters_count: 'Clusters',
    innovations_count: 'Innovaciones',
    avg_novelty: 'Novedad promedio',
    theme: 'Tema',
    language: 'Idioma',
    notifications: 'Notificaciones',
    voice_input: 'Entrada de voz',
    image_upload: 'Carga de imágenes',
    auto_clustering: 'Agrupación automática',
    allow_data_sharing: 'Permitir compartir datos para investigación',
    usage_analytics: 'Analíticas de uso',
    public_profile: 'Perfil público',
    export_my_data: 'Exportar mis datos',
    delete_account: 'Eliminar cuenta',
    change_password: 'Cambiar contraseña',
    gemini_api_key: 'Clave API de Gemini',
    openai_api_key: 'Clave API de OpenAI',
    test_gemini_key: 'Probar clave Gemini',
    test_openai_key: 'Probar clave OpenAI',
    save_settings: 'Guardar configuración',
    saving: 'Guardando...',
  },
  fr: {
    // Common
    save: 'Enregistrer',
    cancel: 'Annuler',
    delete: 'Supprimer',
    edit: 'Modifier',
    create: 'Créer',
    loading: 'Chargement...',
    error: 'Erreur',
    success: 'Succès',
    warning: 'Avertissement',
    info: 'Information',
    
    // Navigation
    dashboard: 'Tableau de bord',
    ideas: 'Idées',
    clusters: 'Clusters',
    innovation: 'Innovation',
    visualization: 'Visualisation',
    settings: 'Paramètres',
    login: 'Connexion',
    register: 'S\'inscrire',
    logout: 'Déconnexion',
    
    // Settings
    settings_title: 'Paramètres',
    profile_settings: 'Paramètres du profil',
    preferences: 'Préférences',
    privacy_settings: 'Paramètres de confidentialité',
    data_management: 'Gestion des données',
    security: 'Sécurité',
    api_configuration: 'Configuration API',
    your_statistics: 'Vos statistiques',
    total_ideas: 'Idées totales',
    clusters_count: 'Clusters',
    innovations_count: 'Innovations',
    avg_novelty: 'Nouveauté moyenne',
    theme: 'Thème',
    language: 'Langue',
    notifications: 'Notifications',
    voice_input: 'Saisie vocale',
    image_upload: 'Téléchargement d\'images',
    auto_clustering: 'Clustering automatique',
    allow_data_sharing: 'Autoriser le partage de données pour la recherche',
    usage_analytics: 'Analytiques d\'utilisation',
    public_profile: 'Profil public',
    export_my_data: 'Exporter mes données',
    delete_account: 'Supprimer le compte',
    change_password: 'Changer le mot de passe',
    gemini_api_key: 'Clé API Gemini',
    openai_api_key: 'Clé API OpenAI',
    test_gemini_key: 'Tester la clé Gemini',
    test_openai_key: 'Tester la clé OpenAI',
    save_settings: 'Enregistrer les paramètres',
    saving: 'Enregistrement...',
  },
  de: {
    // Common
    save: 'Speichern',
    cancel: 'Abbrechen',
    delete: 'Löschen',
    edit: 'Bearbeiten',
    create: 'Erstellen',
    loading: 'Laden...',
    error: 'Fehler',
    success: 'Erfolg',
    warning: 'Warnung',
    info: 'Information',
    
    // Navigation
    dashboard: 'Dashboard',
    ideas: 'Ideen',
    clusters: 'Cluster',
    innovation: 'Innovation',
    visualization: 'Visualisierung',
    settings: 'Einstellungen',
    login: 'Anmelden',
    register: 'Registrieren',
    logout: 'Abmelden',
    
    // Settings
    settings_title: 'Einstellungen',
    profile_settings: 'Profil-Einstellungen',
    preferences: 'Einstellungen',
    privacy_settings: 'Datenschutz-Einstellungen',
    data_management: 'Datenverwaltung',
    security: 'Sicherheit',
    api_configuration: 'API-Konfiguration',
    your_statistics: 'Ihre Statistiken',
    total_ideas: 'Gesamte Ideen',
    clusters_count: 'Cluster',
    innovations_count: 'Innovationen',
    avg_novelty: 'Durchschn. Neuheit',
    theme: 'Design',
    language: 'Sprache',
    notifications: 'Benachrichtigungen',
    voice_input: 'Spracheingabe',
    image_upload: 'Bild-Upload',
    auto_clustering: 'Automatisches Clustering',
    allow_data_sharing: 'Datenaustausch für Forschung erlauben',
    usage_analytics: 'Nutzungsanalytik',
    public_profile: 'Öffentliches Profil',
    export_my_data: 'Meine Daten exportieren',
    delete_account: 'Konto löschen',
    change_password: 'Passwort ändern',
    gemini_api_key: 'Gemini API-Schlüssel',
    openai_api_key: 'OpenAI API-Schlüssel',
    test_gemini_key: 'Gemini-Schlüssel testen',
    test_openai_key: 'OpenAI-Schlüssel testen',
    save_settings: 'Einstellungen speichern',
    saving: 'Speichern...',
  },
};

export const LanguageProvider = ({ children }) => {
  const getTranslation = (key, lang = 'en') => {
    return translations[lang]?.[key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ getTranslation }}>
      {children}
    </LanguageContext.Provider>
  );
};
